name: lando-php
events:
  post-start:
    - defaults: php -i | grep memory_limit | grep -e "-1"
services:
  defaults:
    type: php
  cli:
    type: php
    via: cli
  cliold:
    type: php:5.6
    via: cli
  custom:
    type: php:7.1
    via: nginx
    ssl: true
    xdebug: true
    webroot: web
    config:
      php: config/php.ini
    overrides:
      image: devwithlando/php:7.1-fpm-2
      environment:
        DUALBLADE: maxim
        OTHER: thing
  custom_nginx:
    build_as_root:
      - mkdir -p /app/test && touch /app/test/managed_build_step
    overrides:
      environment:
        MORE: things
        OTHER: stuff
  custom74:
    type: php:7.4
  composer:
    type: php:7.0
    composer:
      phpunit/phpunit: "*"
tooling:
  php:
    service: defaults
