<?php
/**
 * @file
 * Install, update and uninstall functions for the testing profile.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function testing_install() {
  // Allow visitor account creation, but with administrative approval.
  config_set('system.core', 'user_register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL);
}
