#!/bin/bash

# Unset some possibly bad things
unset DYLD_LIBRARY_PATH
unset LD_LIBRARY_PATH

# After installation we need to move our installed binary elsewhere
#
# This is needed until we can do proper signing of the lando binary pkg which
# causes notarization to fail
#
# See: https://github.com/zeit/pkg/issues/128
mkdir -p /usr/local/bin
mv -f /usr/local/bin/lando /usr/local/bin/lando
chmod +x /usr/local/bin/lando

# Fin
