#!/bin/bash

# Unset some possibly bad things
unset DYLD_LIBRARY_PATH
unset LD_LIBRARY_PATH

ln -sf "$HOME/.lando/bin/lando-%LANDO_VERSION%" "$HOME/.lando/bin/lando"
chmod +x "$HOME/.lando/bin/lando"

"$HOME/.lando/bin/lando" shellenv --add

# Fin
