#!/bin/bash

# Unset some possibly bad things
unset DYLD_LIBRARY_PATH
unset LD_LIBRARY_PATH

# perms
sudo chmod +x /usr/local/bin/lando

# shellenv
sudo -iu "$USER" /usr/local/bin/lando shellenv --add > /tmp/lando-install.log
sudo -iu "$USER" /usr/local/bin/lando --clear

# Fin
exit 0
