name: lando
env_file:
  - lando.env
excludes:
  - node_modules
services:
  cli:
    type: node:14
    build:
      - npm ci
    scanner: false
    ssl: true
    sslExpose: false
    overrides:
      environment:
        LANDO_API: https://api.lando.dev
      ports:
        - '8021:8021'
tooling:
  node:
    service: cli
  npm:
    service: cli
