name: lando
env_file:
  - lando.env
excludes:
  - node_modules
proxy:
  cli:
    - docs.lndo.site:8021
services:
  cli:
    type: node:14
    build:
      - yarn install
    scanner: false
    ssl: true
    sslExpose: false
    overrides:
      environment:
        LANDO_API: https://api.lando.dev
      ports:
        - '8021:8021'
tooling:
  docs:
    service: cli
    cmd: yarn dev:docs
    description: Launch the documentation site
  node:
    service: cli
  vuepress:
    service: cli
  yarn:
    service: cli
