name: lando-redis
services:
  defaults:
    type: redis
  patch:
    type: redis:4.0.11
  custom:
    type: redis:4
    portforward: true
    persist: true
    config:
      server: config/redis.conf
  custom6:
    type: redis:6
