#!/bin/sh

set -e
set -u

# Remove the service if it hasn't been already
update-rc.d lando remove > /dev/null || true

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
  systemctl --system daemon-reload > /dev/null || true
fi

# Totally wipe out /usr/share/lando on a purge
if [ "$1" = "purge" ] ; then
  rm -rf /usr/share/lando
fi

# Remove config directory
rm -rf "$HOME/.lando"
