#!/bin/bash

# Scripts to run after we install Lando

set -e -x

LANDO_ROOT=/usr/share/lando
PATH=$PATH:/usr/local/bin
TERM=xterm

# Set some permissions
chmod 755 -R "$LANDO_ROOT"

# Symlink all our binaries
mkdir -p /usr/local/bin
ln -sf "$LANDO_ROOT/bin/lando" /usr/local/bin/lando

# Strictly grab all sudoers
SUDOERS=$(awk -F':' '$1 == "sudo" {print $4}' /etc/group)

# Transform sudoers into IFS default separation and loop
for u in ${SUDOERS//,/ }
do
  usermod -a -G docker $u
done

# Generate a Root CA
mkdir -p $LANDO_ROOT/certs

docker run -d --rm \
  -e COUNTY="BE" \
  -e STATE="Bespin" \
  -e LOCATION="Cloud City" \
  -e ORGANISATION="Tibanna Mining Corp" \
  -e ISSUER_CN="Lando" \
  -e PUBLIC_CN="devwithlando.io" \
  -e ISSUER_NAME="Calrissian" \
  -e PUBLIC_NAME="Lando" \
  -v $LANDO_ROOT/certs:/etc/ssl/certs \
  pgarrett/openssl-alpine

# Well I don't trust him either, and he's my friend...
cp $LANDO_ROOT/certs/root.crt /usr/local/share/ca-certificates/root.crt
update-ca-certificates

# @TODO: Wait for GUI
# Add an entry to the system menu
# XDG_DESKTOP_MENU="$(which xdg-desktop-menu 2> /dev/null)"
# if [ ! -x "$XDG_DESKTOP_MENU" ]; then
#   echo "WARNING: Could not find xdg-desktop-menu" >&2
# else
   # We need this directory to exist
   # mkdir -p /usr/share/desktop-directories/
   # Set the menu things
   # "$XDG_DESKTOP_MENU" install --novendor --mode system /usr/share/applications/lando.desktop
   # "$XDG_DESKTOP_MENU" forceupdate --mode system
#fi
