#!/bin/bash

# Scripts to run after we install Lando

set -e -x

LANDO_ROOT=/usr/share/lando
PATH=$PATH:/usr/local/bin
TERM=xterm

# Set some permissions
chmod 755 -R "$LANDO_ROOT"

# Symlink all our binaries
mkdir -p /usr/local/bin
ln -sf "$LANDO_ROOT/bin/lando" /usr/local/bin/lando

# Strictly grab all sudoers
SUDOERS=$(awk -F':' '$1 == "sudo" {print $4}' /etc/group)

# Transform sudoers into IFS default separation and loop
for u in ${SUDOERS//,/ }
do
  usermod -a -G docker $u
done

# Bump this for ES search things
MAX_MAP_COUNT=262144
MMC_PARAMETER_PATH=/proc/sys/vm/max_map_count
if [ -f "$MMC_PARAMETER_PATH" ] && [ "$(sysctl -n vm.max_map_count)" -lt "$MAX_MAP_COUNT" ]; then
  if [ -w "$MMC_PARAMETER_PATH" ]; then
    sysctl -w vm.max_map_count=$MAX_MAP_COUNT
  else
    CURRENT_VALUE=$(sysctl -n vm.max_map_count)
    cat <<EOF
The value of the kernel parameter 'vm.max_map_count' is currently set to $CURRENT_VALUE.
For best performance, we recommend that this be set to at least $MAX_MAP_COUNT.
We attempted to set this value automatically, but were unable.
To try to set this value yourself, run the following command:

            sysctl -w vm.max_map_count=$MAX_MAP_COUNT
EOF
  fi
fi

# @TODO: Wait for GUI
# Add an entry to the system menu
# XDG_DESKTOP_MENU="$(which xdg-desktop-menu 2> /dev/null)"
# if [ ! -x "$XDG_DESKTOP_MENU" ]; then
#   echo "WARNING: Could not find xdg-desktop-menu" >&2
# else
   # We need this directory to exist
   # mkdir -p /usr/share/desktop-directories/
   # Set the menu things
   # "$XDG_DESKTOP_MENU" install --novendor --mode system /usr/share/applications/lando.desktop
   # "$XDG_DESKTOP_MENU" forceupdate --mode system
#fi
