# New build events example
name: newevents
recipe: wordpress
config:
  webroot: web

events:
  # Verify WP-cli exists
  # eg that internal build steps have completed first
  pre-start:
    - wp --version
    - cat /app/TESTFILE && rm /app/TESTFILE
  # Verify the install with WP-CLI
  post-start:
    - wp core is-installed --path=/app/web && echo "WE ARE INSTALLED!"

services:
  appserver:
    # Before the app starts lets get the codebase if we need it
    install_dependencies_as_me: |
      if [ ! -d "/app/web" ]; then
        mkdir -p /app/web && cd /app/web
        wp core download
      fi
      echo "THIS SHOULD EXIST" > /app/TESTFILE
    # After the app starts lets try to install and setup wordpress
    # Running here *SHOULD* ensure that the database is up
    run_as_me: |
      if [ ! -d "/app/web/wp-config.php" ]; then
        sleep 10
        wp core config --path=/app/web --dbhost=database --dbname=wordpress --dbuser=wordpress --dbpass=wordpress
        chmod 644 wp-config.php
        wp core install --path=/app/web --url=newevents.lndo.site --title="CAPTAIN! THERE BE WHALES HERE!" --admin_name=admin --admin_password=a --admin_email=mike@devwithlando.io
        cd /app/web/wp-content && mkdir uploads && chgrp www-data uploads/
        chmod 755 uploads/
      fi
