name: mysql
sharing:
  html:
    local: www
    remote: /usr/share/nginx/html
proxy:
  html:
    - port: 80/tcp
      default: true
    - port: 443/tcp
      default: true
      secure: true
services:
  html:
    type: nginx
    ssl: true
  database:
    type: mysql
    portforward: 3311
    creds:
      user: pirog
      password: pirog
      database: pirog
