# Laravel recipe
name: laravel

# Start with the default laravel recipe
recipe: laravel

# Configure the laravel recipe
config:

  # See: https://laravel.com/docs/5.4/installation#server-requirements

  # Optionally specify the php version to use.
  #
  # If ommitted this will default to the latest php version supported by laravel.
  # Consult the `php` service to see what versions are available. Note that all
  # such versions may not be supported in Laravel 7 so YMMV.
  #
  # See: https://laravel.com/docs/5.4/installation#server-requirements
  #
  # NOTE: that this needs to be wrapped in quotes so that it is a string
  #
  php: '7.0'

  # Optionally specify whether you want to serve drupal via nginx or apache
  #
  # If ommitted this will default to the latest apache
  #
  # See: https://laravel.com/docs/5.4/installation#web-server-configuration
  #
  via: nginx

  # Optionally specify the location of the webroot relative to your approot.
  # For Laravel this is usually 'public'
  #
  # If ommitted this will be your approot itself.
  #
  webroot: public

  # Optionally specify a primary database, this can be one of:
  #
  #   - `mysql`
  #   - `mariadb`
  #   - `postgres`
  #
  # If ommitted this will not install a db for you.
  #
  # see: https://laravel.com/docs/5.4/database#configuration
  #
  database: mariadb:10.1

  # Optionally specify a primary caching backend, this can be one of:
  #
  #   - `redis`
  #   - `memcached`
  #
  # If ommitted this will not install a db for you
  #
  # see: https://laravel.com/docs/5.4/cache#configuration
  cache: redis

  # Optionally activate xdebug
  xdebug: true

  # Optionally mix in your own config files
  #
  # If ommitted this will use the default Laravel config files for the respective
  # services.
  #
  # Definitely consult the relevant documentaion for each service to make sure
  # you are specifying the correct value for the config. As an example `mysql`
  # will want a directory while `postgres` will want a specific config file.
  #
  # conf:
    # server: config/laravel.conf
    # database: config/mysql
    # php: config/php.ini

# The Laravel recipe is super slick but we want to augment this recipe so we can
# run our front end tooling magix
services:
  node:
    type: node:6.10
tooling:
  node:
    service: node
  npm:
    service: node
