# Name of the events example
name: events

# Start with the lemp recipe and some recipe config
recipe: lemp
config:
  via: nginx
  php: 7.1
  webroot: www

# Add in some custom event scripting
events:

  # Run some commands after `lando db-import`
  post-db-import:

    # Run `drush version` on the appserver service
    - appserver: drush version

    # Print out "test this command" on a service determined by lando
    #
    # If no service is specified in the format {SERVICENAME: CMD} lando will
    # attempt to determine the best service to run the command on.
    #
    # If the event is a tooling command (as is the case here) lando will run
    # this command on that service. Otherwise lando will use `appserver`
    - echo "test this command"

  # Run some commands after `lando test`
  post-test:
    - echo "Tests complete!"

  # Run some commands after `lando start`
  post-start:
    - echo "App restarted!"

# Provide a trivial command to help test the event framework
tooling:
  test:
    description: Test command for event framework
    cmd: true
    service: appserver
