name: lando-go
services:
  defaults:
    type: go
    command: go run /app/http.go
  patch:
    type: go:1.13.9
  custom:
    type: go
    ssl: true
    command: go run /app/https.go
  cli:
    type: go
