<?php

/**
 * @file
 * Install, update and uninstall functions for the update_test_2 module.
 */

/**
 * Implements hook_update_dependencies().
 *
 * @see update_test_1_update_dependencies()
 * @see update_test_3_update_dependencies()
 */
function update_test_2_update_dependencies() {
  // Combined with update_test_3_update_dependencies(), we are declaring here
  // that these two modules run updates in the following order:
  // 1. update_test_2_update_1000()
  // 2. update_test_3_update_1000()
  // 3. update_test_2_update_1001()
  // 4. update_test_2_update_1002()
  $dependencies['update_test_2'][1001] = array(
    'update_test_3' => 1000,
  );

  // These are coordinated with the corresponding dependencies declared in
  // update_test_1_update_dependencies().
  $dependencies['system'][1000] = array(
    'update_test_2' => 1001,
  );
  $dependencies['system'][1001] = array(
    'update_test_1' => 1001,
  );

  return $dependencies;
}

/**
 * Dummy update_test_2 update 1000.
 */
function update_test_2_update_1000() {
}

/**
 * Dummy update_test_2 update 1001.
 */
function update_test_2_update_1001() {
}

/**
 * Dummy update_test_2 update 1002.
 */
function update_test_2_update_1002() {
}
