:: Batch file

:: Print out some helpful appveyor info
ECHO "APPVEYOR_REPO_TAG: %APPVEYOR_REPO_TAG%"
ECHO "APPVEYOR_REPO_TAG_NAME: %APPVEYOR_REPO_TAG_NAME%"
ECHO "APPVEYOR_REPO_BRANCH: %APPVEYOR_REPO_BRANCH%"
ECHO "APPVEYOR_PROJECT_SLUG: %APPVEYOR_PROJECT_SLUG%"
ECHO "APPVEYOR_BUILD_FOLDER: %APPVEYOR_BUILD_FOLDER%"
ECHO "PATH: %PATH%"
