#!/bin/bash

# Print out some helpful travis info
echo "TRAVIS_TAG: $TRAVIS_TAG"
echo "TRAVIS_BRANCH: $TRAVIS_BRANCH"
echo "TRAVIS_PULL_REQUEST: $TRAVIS_PULL_REQUEST"
echo "TRAVIS_REPO_SLUG: $TRAVIS_REPO_SLUG"
echo "TRAVIS_BUILD_DIR: $TRAVIS_BUILD_DIR"
echo "TRAVIS_OS_NAME: $TRAVIS_OS_NAME"
echo "PATH: $PATH"
