#!/bin/bash

# Print out some helpful travis info
echo "TRAVIS_TAG: $TRAVIS_TAG"
echo "TRAVIS_BRANCH: $TRAVIS_BRANCH"
echo "TRAVIS_PULL_REQUEST: $TRAVIS_PULL_REQUEST"
echo "TRAVIS_REPO_SLUG: $TRAVIS_REPO_SLUG"
echo "TRAVIS_BUILD_DIR: $TRAVIS_BUILD_DIR"
echo "TRAVIS_OS_NAME: $TRAVIS_OS_NAME"
echo "TRAVIS_COMMIT_RANGE: $TRAVIS_COMMIT_RANGE"

# And other stuff
echo "CHANGED_FILES: $CHANGED_FILES"
echo "CHANGED_FILES2: $CHANGED_FILES2"
echo "PIROG: $PIROG"

echo "PATH: $PATH"

export LANDO="thing"
