<?php

/**
 * @file
 * Helper module for entity cache tests.
 */

/**
 * Implements hook_watchdog().
 *
 * This hook is called during module_enable() and since this hook
 * implementation is invoked, we have to expect that this module and dependent
 * modules have been properly installed already. So we expect to be able to
 * retrieve the entity information that has been registered by the required
 * dependency module.
 *
 * @see EnableDisableTestCase::testEntityCache()
 * @see entity_cache_test_dependency_entity_info()
 */
function entity_cache_test_watchdog($log_entry) {
  if ($log_entry['type'] == 'system' && $log_entry['message'] == '%module module installed.') {
    $info = entity_get_info('entity_cache_test');
    // Store the information in a system variable to analyze it later in the
    // test case.
    variable_set('entity_cache_test', $info);
  }
}
