<?php

/**
 * Implements hook_requirements().
 */
function requirements1_test_requirements($phase) {
  $requirements = array();
  // Ensure translations don't break during installation.
  $t = get_t();

  // Always fails requirements.
  if ('install' == $phase) {
    $requirements['requirements1_test'] = array(
      'title' => $t('Requirements 1 Test'),
      'severity' => REQUIREMENT_ERROR,
      'description' => $t('Requirements 1 Test failed requirements.'),
    );
  }

  return $requirements;
}
