<?php

/**
 * @file
 * Install, update and uninstall functions for the blog module.
 */

/**
 * Implements hook_install().
 */
function blog_install() {
  // Ensure the blog node type is available.
  node_types_rebuild();
  $types = node_type_get_types();
  node_add_body_field($types['blog']);
}

/**
 * Implements hook_uninstall().
 */
function blog_uninstall() {
  variable_del('blog_block_count');
}
