#!/bin/bash

# Unset some things that could S the P
unset DYLD_LIBRARY_PATH
unset LD_LIBRARY_PATH
unset ${!DOCKER_*}

# Define some config
PATH=$PATH:/usr/local/bin
TERM=xterm

# Kill docker if running
killall Docker || true

# Get the user originale
declare -r console_user=$(stat -f '%Su' /dev/console)

# Set some docker things
declare -r docker_bundle_dir=/Applications/Docker.app/Contents
declare -r docker=${docker_bundle_dir}/Resources/bin/docker

# Make sure some core directories exist
sudo mkdir -p /usr/local/bin

# Run dockers unattended installer
sudo /Applications/Docker.app/Contents/MacOS/install --user="${console_user}"

# Launch docker
sudo -u ${console_user} open -a /Applications/Docker.app
sudo chown -R ${console_user} "/Users/${console_user}/.docker" || true

# Wait for docker to be ready
NEXT_WAIT_TIME=0
until ${docker} info >/dev/null || [ $NEXT_WAIT_TIME -eq 10 ]; do
  sleep $(( NEXT_WAIT_TIME++ ))
done

# Fin
