name: Automatic Issue Triage
on:
  issues:
    types:
      - labeled

jobs:
  issue-triage:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        router:
          - acquia:acquia
          - apache:apache
          - compose:compose
          - documentation:docs
          - dotnet:dotnet
          - elasticsearch:elasticsearch
          - go:go
          - lagoon:lagoon
          - lamp:lamp
          - lemp:lemp
          - mailhog:mailhog
          - mariadb:mariadb
          - memcached:memcached
          - mongo:mongo
          - mssql:mssql
          - mysql:mysql
          - nginx:nginx
          - node:node
          - pantheon:pantheon
          - php:php
          - platformsh:platformsh
          - postgres:postgres
          - python:python
          - solr:solr

    steps:
      - name: Manual Action Test
        id: test_action
        uses: lando/transfer-issue-action@v2
        with:
          token: ${{ secrets.TRANSFER_ISSUE_TOKEN }}
          router: ${{ matrix.router }}
          apply_label: Needs Triage
