name: Test macOS Installer Build

on:
  pull_request:

jobs:
  test-macos-installer:
    runs-on: ${{ matrix.os }}
    env:
      APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
      APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
      APPLE_TEAM_ID: FY8GAUX282
      TERM: xterm
    strategy:
      matrix:
        os:
          - macos-12
        node-version:
          - '16'
        arch:
          - x64
          - arm64

    steps:
      # Install deps and cache
      # Eventually it would be great if these steps could live in a separate YAML file
      # that could be included in line to avoid code duplication
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # Import ENVVARS from build.env
      # @NOTE: We do this so there is a single place to update versions
      - name: Import build version envvars
        id: import-env
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < BUILD.env

      # Build and prep the release
      - name: Rewrite the version based on the tag
        run: node scripts/dev-version.js
      - name: Import and verify certs
        run: scripts/import-macos-certs.sh
      - name: Assemble pieces
        run: scripts/assemble-macos.sh --arch ${{ matrix.arch }}
      - name: Sign package
        run: |
          # Rename some things
          mv build/installer/dmg/LandoInstaller.pkg build/installer/dmg/UnsignedLandoInstaller.pkg
          # Sign
          productsign --sign "$APPLE_TEAM_ID" build/installer/dmg/UnsignedLandoInstaller.pkg build/installer/dmg/LandoInstaller.pkg
          # Verify
          pkgutil --check-signature build/installer/dmg/LandoInstaller.pkg
          # Remove unsigned
          rm -f build/installer/dmg/UnsignedLandoInstaller.pkg
      - name: Create DMG
        run: |
          mkdir -p dist
          scripts/create-dmg.sh build/installer/dmg
      - name: Sign DMG
        run: |
          # Sign
          codesign -s "$APPLE_TEAM_ID" -v dist/lando.dmg
          # Verify
          codesign -v dist/lando.dmg
      - name: Notarize DMG
        env:
          APPLE_NOTARY_USER: ${{ secrets.APPLE_NOTARY_USER }}
          APPLE_NOTARY_PASSWORD: ${{ secrets.APPLE_NOTARY_PASSWORD }}
        run: scripts/notarize.sh dist/lando.dmg

      # Create and upload releases
      - name: Create releases
        run: |
          mkdir -p releases
          cp -f "dist/lando.dmg" "releases/lando-build-test-${{ matrix.arch }}.dmg"
          ls -lsa releases
      # Upload back to Actions
      - name: Upload build snapshot as Actions artifact
        uses: actions/upload-artifact@v3
        with:
          name: lando-build-${{ github.sha }}-${{ matrix.arch}}.dmg
          path: releases
          if-no-files-found: error
          retention-days: 30
      # Upload releases to S3
      - name: Configure S3 Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload releases to S3
        shell: bash
        run: |
          aws s3 sync releases s3://files.lando.dev/installer
          # Below is for backwards compatibility
          aws s3 sync releases s3://files.lando.dev
