name: Automatic Submodule Update
on:
  schedule:
    - cron: '8 14 * * *'

jobs:
  auto-update-submodules:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-22.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PIROG_TOKEN }}
          fetch-depth: 0
          submodules: true
      - name: Setup git user
        shell: bash
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Update submodules
        shell: bash
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit and push
        shell: bash
        run: |
          git add .
          git commit \
          -m "Autoupdated submodule pointer"
          git push origin main


