#!/bin/sh

set -e

# Get the lando logger
. /helpers/log.sh

# Set the module
LANDO_MODULE="drush"

echo ""
lando_yellow "This version of drupal prefers you have a site-local install of drush!"
echo ""
echo "Run the following command and try drush again:"
lando_green "lando composer require drush/drush"

exit 1
